version: 2
updates:
    - directory: /
      package-ecosystem: npm
      schedule:
          interval: weekly
      versioning-strategy: increase
    - directory: /ui
      package-ecosystem: npm
      schedule:
          interval: weekly
      versioning-strategy: increase
