version: 2
updates:
    - directory: /
      package-ecosystem: npm
      schedule:
          interval: weekly
      versioning-strategy: increase
      commit-message:
          prefix: chore
          prefix-development: chore
          include: scope
