name: Deploy Release

on:
    push:
        tags:
            - "v*"

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-region: eu-west-2
                  role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
            - uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.3.7
                  terraform_wrapper: false
            - uses: actions/cache@v3
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  yarn ci
            - name: Run deployment
              env:
                  TF_VAR_mongodb_private_key: ${{ secrets.MONGODB_PRIVATE_KEY }}
                  TF_VAR_mongodb_public_key: ${{ secrets.MONGODB_PUBLIC_KEY }}
              run: |
                  previous_tag=$(git tag | sort -V | tail -n 2 | head -n 1)
                  if [ -n "$previous_tag" ]; then
                    lerna run deploy --since="$previous_tag" -- -e prod
                  else
                    lerna run deploy -- -e prod
                  fi
