name: Validate and Deploy

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - uses: actions/cache@v3
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  npm run ci
            - name: Run formatters
              run: |
                  lerna run format:check --since=origin/master
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - uses: actions/cache@v3
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  npm run ci
            - name: Run linters
              run: |
                  lerna run lint --since=origin/master
    validate:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                  aws-region: eu-west-2
                  role-to-assume: ${{ secrets.UI_DEPLOY_ROLE_ARN }}
            - uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.3.7
            - uses: actions/cache@v3
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  npm run ci
            - name: Run validators
              run: |
                  lerna run validate --since=origin/master
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - uses: actions/cache@v3
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  npm run ci
            - name: Build Project
              run: |
                  lerna run build --since=origin/master
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - uses: actions/cache@v3
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  npm run ci
            - name: Run Unit Tests
              run: |
                  lerna run test --since=origin/master
    deploy-dryrun:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                  aws-region: eu-west-2
                  role-to-assume: ${{ secrets.UI_DEPLOY_ROLE_ARN }}
            - uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.3.7
            - uses: actions/cache@v3
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  npm run ci
            - name: Run dry run deployment
              run: |
                  lerna run deploy:plan --since=origin/master -- -e prod
    deploy:
        runs-on: ubuntu-latest
        needs: [format, lint, validate, build, test, deploy-dryrun]
        if: ${{ github.ref == 'refs/heads/master' }}
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                  aws-region: eu-west-2
                  role-to-assume: ${{ secrets.UI_DEPLOY_ROLE_ARN }}
            - uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.3.7
                  terraform_wrapper: false
            - uses: actions/cache@v3
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  npm run ci
            - name: Run deployment
              run: |
                  lerna run deploy --since=origin/master -- -e prod
