name: Validate and Deploy

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: Run formatters
              run: |
                  npm run format:check
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: Install Dependencies
              run: |
                  npm ci
            - name: Run linters
              run: |
                  npm run lint
