name: Validate and Create Release

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  yarn install
            - name: Run formatters
              run: |
                  if [ "${{ github.ref }}" != "refs/heads/master" ]; then
                    lerna run format:check --since=origin/master
                  else
                    previous_tag=$(git tag | sort -V | tail -n 1)
                    if [ -n "$previous_tag" ]; then
                      lerna run format:check --since="$previous_tag"
                    else
                      lerna run format:check
                    fi
                  fi
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  yarn install
            - name: Run linters
              run: |
                  if [ "${{ github.ref }}" != "refs/heads/master" ]; then
                    lerna run lint --since=origin/master
                  else
                    previous_tag=$(git tag | sort -V | tail -n 1)
                    if [ -n "$previous_tag" ]; then
                      lerna run lint --since="$previous_tag"
                    else
                      lerna run lint
                    fi
                  fi
    commit-lint:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  yarn install
            - name: Lint Commits
              run: |
                  yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
    validate:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-region: eu-west-2
                  role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
            - uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.3.7
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  yarn install
            - name: Run validators
              run: |
                  if [ "${{ github.ref }}" != "refs/heads/master" ]; then
                    lerna run validate --since=origin/master
                  else
                    previous_tag=$(git tag | sort -V | tail -n 1)
                    if [ -n "$previous_tag" ]; then
                      lerna run validate --since="$previous_tag"
                    else
                      lerna run validate
                    fi
                  fi
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  yarn install
            - name: Build Project
              run: |
                  if [ "${{ github.ref }}" != "refs/heads/master" ]; then
                    lerna run build --since=origin/master
                  else
                    previous_tag=$(git tag | sort -V | tail -n 1)
                    if [ -n "$previous_tag" ]; then
                      lerna run build --since="$previous_tag"
                    else
                      lerna run build
                    fi
                  fi
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  yarn install
            - name: Run Unit Tests
              run: |
                  if [ "${{ github.ref }}" != "refs/heads/master" ]; then
                    lerna run test --since=origin/master
                  else
                    previous_tag=$(git tag | sort -V | tail -n 1)
                    if [ -n "$previous_tag" ]; then
                      lerna run test --since="$previous_tag"
                    else
                      lerna run test
                    fi
                  fi
    deploy-dryrun:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-region: eu-west-2
                  role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
            - uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.3.7
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  yarn install
            - name: Run dry run deployment
              env:
                  TF_VAR_mongodb_private_key: ${{ secrets.MONGODB_PRIVATE_KEY }}
                  TF_VAR_mongodb_public_key: ${{ secrets.MONGODB_PUBLIC_KEY }}
              run: |
                  if [ "${{ github.ref }}" != "refs/heads/master" ]; then
                    lerna run deploy:plan --since=origin/master -- -e prod
                  else
                    previous_tag=$(git tag | sort -V | tail -n 1)
                    if [ -n "$previous_tag" ]; then
                      lerna run deploy:plan --since="$previous_tag" -- -e prod
                    else
                      lerna run deploy:plan -- -e prod
                    fi
                  fi
    create-release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        needs: [format, lint, validate, build, test, deploy-dryrun]
        if: ${{ github.ref == 'refs/heads/master' }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.12.1"
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-dependencies-v1-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-dependencies-v1-
            - name: Install Dependencies
              run: |
                  yarn install
            - name: Create Tags
              env:
                  GITHUB_TOKEN: ${{ secrets.TAG_TOKEN }}
              run: |
                  yarn semantic-release
